

CREATE TABLE IF NOT EXISTS token(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token TEXT NOT NULL CHECK (token <> '')
)

CREATE TABLE IF NOT EXISTS user(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    last_name TEXT NOT NULL CHECK (last_name <> ''),
    prefix TEXT NOT NULL CHECK (prefix <> ''),
    email TEXT NOT NULL CHECK (email <> ''),
    token_id TEXT REFERENCES token(id)
);

CREATE TABLE IF NOT EXISTS area(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    area_name TEXT NOT NULL CHECK (area_name <> ''),
    abbreviation TEXT NOT NULL CHECK (abbreviation <> ''),
    responsable_id TEXT REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS activities_programm_annual(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    activity_name TEXT NOT NULL CHECK (activity_name <> ''),
    enumeration TEXT NOT NULL CHECK (enumeration <> ''),
    start_week INTEGER,
    end_week INTEGER
);

CREATE TABLE IF NOT EXISTS annual_programm(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL CHECK (title <> ''),
    total_weeks INTEGER,
    
);